name: Github Secrets Unni 

on:
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret
      run: |
          echo "UNNI_TOP_SECRET: ${{ secrets.UNNI_TOP_SECRET }}"
          echo "i_dont_exist: ${{ secrets.i_dont_exist }}"

    - name: Print secret as an environment variable
      run: |
          echo "UNNI_TOP_SECRET: $UNNI_TOP_SECRET"
      env:
          MY_TOP_SECRET: ${{ secrets.UNNI_TOP_SECRET }}