name: 'Custom Env Vars Unni'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value-1
  TOP_SECRET: i-am-top-secret-dont-disclose

jobs:
  mainjob:
    name: 'Print the env Vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2


    steps:
    - name: print-value-of-env-vars
      run: |
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
        echo "testvar $testvar"
        echo "testvar ${{env.testvar}}"
      env:
        First_Name: Student
        testvar: value-3