name: Deploy Infra Unni Workflow

on:
  workflow_dispatch:

env:
  storageNamePrefix: 'unnitest'
  resourceGroupName: 'rg-unni-test'

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # Login into Azure
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep
      - name: Bicep Deploy
        uses: Azure/bicep-deploy@v2.2.0
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: env.resourceGroupName
          template: './infra/templates/deploy_envt.bicep'
          parameters: ./infra/envts/production/deploy_envt.parameters.json storageNamePrefix=${{ env.storageNamePrefix }}
          
