# This is a simple workflow 

name: 'GitHub Workflow Demo for Unni'

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps: 
    - name: runscript-to-say-hello
      run:  echo "Howdy GitHub Actions"
